### ISSUE TITLE
flashen firmware / foutmeldingen/waarschuwingen compiler

### ISSUE THREAD

**Issue by i32x** [thieu-b55/Slimme-meter-ESP32-V2#1]

**Comment by i32x** [comment]
wat moeilijkheden met invullen,
met vriendelijke groet,

**Comment by thieu-b55** [comment]
Nieuwe .bin files geupload, probleem zou opgelost moeten zijn.
Sorry voor het ongemak.

Foutmelding lijn 377.
Warning voor het ontbreken van

uint32_t idle_core_mask

voor meer uitleg zie 
https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-reference/system/wdts.html#structures
