### ISSUE TITLE
Connectie ESP32 - P1

### ISSUE THREAD

**Issue by wannestal** [thieu-b55/Slimme-meter-ESP32-V2#3]
Hallo, 

1. hoe is de esp32 verbonden met de P1 poort?
2. wordt de esp32 gevoed met de spanning uit de P1 poort? Ik vraag me af of deze genoeg stroom kan leveren.

mvg
Wannes

**Comment by thieu-b55** [comment]
Zie pagina 9 van bijgevoegde pdf file "Slimme meter ESP32 V2.pdf"

vriendelijke groeten,
thieu-b55
